pretrained_models_path = ""
ILSVRC2012_path = '/n02dat01/public_resource/dataset/ImageNet/'
tiny_imagenet_path = '/share/home/kcli/DATASET/tiny-imagenet-200'
CIFAR100_path = '/share/home/kcli/DATASET/'
# Caltech_100_path = '/share/home/kcli/DATASET/256_ObjectCategories/'
# CIFAR100_path = r"C:\Users\likunchi\work\dataset"
imagenet100_json_path = '/share/home/kcli/DATASET/imagenet/imagenet100_forCL_1.json'
imagenet100_json_path_forBiC = '/share/home/kcli/DATASET/imagenet/imagenet100_forBiC_1.json'
imagenet1000_json_path = '/share/home/kcli/DATASET/imagenet/imagenet1000.json'
Caltech_100_json_path = '/share/home/kcli/DATASET/100_ObjectCategories/Caltech100_from_Caltech256.json'
tiny_imagenet100_forPretrain = '/share/home/kcli/DATASET/tiny-imagenet-200/tiny_imagenet_200_pretrain_dataset.json'
tiny_imagenet100_forCL = '/share/home/kcli/DATASET/tiny-imagenet-200/tiny_imagenet_200_cl_dataset.json'
tiny_imagenet100_path = tiny_imagenet100_forCL